name: Publish release

on:
  release:
    types: [published]

jobs:
  build:
    name: Release published
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: echo "I'm running on publish release"
