name: Push tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Echo something
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: echo "I'm running on push tag"
