name: Deploy preview

on:
  pull_request:
  issue_comment:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: Show GH context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show GH event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.pull_request.body }}

      - name: Extract command
        if: contains(${{ github.event.pull_request.body}}, 'API_PR=')
        run: |
          PR=$(cat ${{ github.event.pull_request.body}} | grep API_PR | head -n1 | cut -d '=' -f2 | cut -d ' ' -f1)
          echo "PR_NUMBER=$PR" >> GITHUB_ENV

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: foo
          recreate: true
          message: The PR will be ${{ env.PR_NUMBER }}

  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
