name: Deploy to production

on:
  workflow-dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: git branch
      - run: git checkout master
      - run: git checkout origin master
