name: Deploy to production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - run: git branch
      - run: git checkout main
      - run: git checkout -B production
      - run: git push origin production --force
