name: Deploy preview

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: Show GH context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Show GH event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.pull_request.body }}

      - name: Extract command
        if: contains(${{ github.event.pull_request.body}}, 'API_PR=')
        run: |
          PR=$(echo "${{ github.event.pull_request.body}}" | grep API_PR | head -n1 | cut -d '=' -f2 | cut -d ' ' -f1)
          echo $PR
          echo "PR_NUMBER=$PR" >> GITHUB_ENV
          echo ${{ env.PR_NUMBER }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: foo
          recreate: true
          message: The PR will be ${{ env.PR_NUMBER }}
