name: Deploy Web to production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Dumb github context
        run: |
          echo '${{ toJSON(github) }}'
      - name: Push main to production branch
        run: |
          git checkout ${{ github.sha }}
          git checkout -B production
          git push origin production --force