name: Deploy Web to production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Push main to production branch
        run: |
          echo {{ github.context }}
          git checkout main
          git checkout -B production
          git push origin production --force