name: A workflow for my Hello World file
on: 
  push:
  workflow_dispatch:
    inputs:
      api-heroku-app:
        description: 'The API the frontend will use. Example: myapp-staging'
        required: true

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Echo variable
        run: |
          echo "-----${{ github.event.inputs.api-heroku-app}}----"
