name: Push on main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Push main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: echo "I'm running on merge main aka deploy staging"
