name: Post PR to Slack

on:
  workflow_dispatch:
  pull_request:

jobs:
  post-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - run: echo "${{ github.context }}"
