name: Publish release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    name: Echo something
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: echo "I'm running on tag and publish release"
