name: Push and PR on main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: Run tests, reports, etc
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Reports - run only on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Adding comment to PR"

  deploy-staging:
    name: Deploy staging
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy staging - run only on merge
        run: echo "Deploy to staging"
