name: Push and PR on main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Echo something
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: run only on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Running only on PR"

      - name: run only on push
        if: ${{ github.event_name == 'push' }}
        run: echo "Running only on push"
