name: Push and PR on main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Push and PR on main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: run only on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Running only on PR"

      - name: run only on push
        if: ${{ github.event_name == 'push' }}
        run: echo "Running only on push"
