name: Push and PR on main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Echo something
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: gem install dpl
      - run: dpl -v

      - run: echo "I'm running on PR on main and push to main"
