name: Push on main and all PRs

on:
  push:
    branches:
      - main
      - "*release**"
    paths:
      - '.github/workflows/test-api.yml'
      - 'api/**'
  pull_request:
    paths:
      - '.github/workflows/test-api.yml'
      - 'api/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: Run tests, reports, etc
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Link to action summary
        run: |
          echo "Dummy file" > dummy.txt
          echo "[CI summary and artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> dummy.txt
          curl --help

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: dummy.txt

      - run: mkdir tmp

      - run: echo "<foo>bar</foo>" > tmp/undercover-checkstyle.xml

      - name: Archive undercover-checkstyle results
        uses: actions/upload-artifact@v2
        with:
          name: undercover-checkstyle
          path: tmp/undercover-checkstyle.xml
          retention-days: 10

  report-on-pr:
    name: Reports - run only on PR
    if: github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: undercover-checkstyle

      - run: cat undercover-checkstyle.xml

  deploy-staging:
    name: Deploy to staging only if main
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying to staging"
      - run: echo '${{ toJSON(github) }}'
