name: Push and PR on main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: show GH event
        run: echo ${{ github.event_name }}

      - name: Run tests, reports, etc
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: mkdir tmp

      - run: echo "<foo>bar</foo>" > tmp/undercover-checkstyle.xml

      - name: Archive undercover-checkstyle results
        uses: actions/upload-artifact@v2
        with:
          name: undercover-checkstyle
          path: undercover-checkstyle.xml
          retention-days: 10

  report-on-pr:
    name: Reports - run only on PR
    if: github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: undercover-checkstyle

      - run: cat undercover-checkstyle.xml

  artifacts-url-comment:
    name: add artifact links to pull request and related issues job
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: windows-2019
    steps:
      - name: add artifact links to pull request
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: Here are the artifacts
          suffix: Have a nice day.
          format: name
          addTo: pull

  deploy-staging:
    name: Deploy staging
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy staging - run only on merge
        run: echo "Deploy to staging"
